openapi: 3.1.0
info:
  title: Student Course Management API
  version: 2.0.0
  description: API for managing groups and students in a course management system.
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /groups:
    get:
      summary: Get list of groups
      operationId: getGroups
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Group"
    post:
      summary: Create a new group
      operationId: createGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateGroup"
      responses:
        "201":
          description: Group created

  /students:
    get:
      summary: Get list of students
      operationId: getStudents
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Student"
    post:
      summary: Create a new student
      operationId: createStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateStudent"
      responses:
        "201":
          description: Student created

  /students/{studentId}/group:
    put:
      summary: Update the group of a specific student
      operationId: updateStudentGroup
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Group"
      responses:
        "200":
          description: Student's group updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Student"

  /students/group:
    put:
      summary: Update the groups of multiple students
      operationId: updateMultipleStudentGroups
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  studentId:
                    type: string
                  group:
                    $ref: "#/components/schemas/Group"
      responses:
        "200":
          description: List of students with updated groups
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Student"

  /students/{studentId}/groups/{groupId}:
    put:
      summary: Associate a specific student with a specific group
      operationId: associateStudentToGroup
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Student associated with the group
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Student"

components:
  schemas:
    Group:
      type: object
      properties:
        id:
          type: string
          example: "G1"
        groupName:
          type: string
          example: "J2"
        groupYear:
          type: string
          example: "2023"
        promotion:
          type: string
          enum: [G, H, J, K]
        studentNb:
          type: integer
          example: 30
        students:
          type: array
          items:
            $ref: "#/components/schemas/Student"
    Student:
      type: object
      properties:
        id:
          type: string
          example: "STD23XXX"
        name:
          type: string
          example: "John Doe"
        sex:
          type: string
          enum: [M, F]
        birthdate:
          type: string
          format: date
          example: "2000-01-01"
        reference:
          type: string
          example: "STD23XXX"
        group:
          $ref: "#/components/schemas/Group"
    CreateGroup:
      allOf:
        - $ref: "#/components/schemas/Group"
        - type: object
          properties:
            id:
              type: string
              example: null
    CreateStudent:
      allOf:
        - $ref: "#/components/schemas/Student"
        - type: object
          properties:
            id:
              type: string
              example: null
